module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: default
cabal-file: project.cabal
version: 1
ghc-args: []
excluded-modules:
- Base9.hs
- BaseEmit.hs
- Setup.hs
- dist/build/autogen/Paths_Transient.hs
